---
- name: Encrypt with KMS play
  hosts: local-servers
#    vars:
#     contents: "{{ lookup('file', '/etc/foo.txt') }}"

  tasks:
    - debug: msg="Region is {{Region}}"
    - debug: msg="Environment is {{Environment}}"
    - debug: msg="User Init in integration section is {{ lookup('ini', 'user section=integration file=../init/users.ini' ) }}"

    - name: Home environment variable
      debug: msg="{{ lookup('env','HOME') }} is an environment variable"

    - name: register output of whoami command
      command: whoami
      register: login
    - debug: var=login.stdout
    - debug: msg="output of whoami command is {{login.stdout}}"
